package juegoia;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ventana extends javax.swing.JFrame {        
    Dibujos d = new Dibujos();    
    String mat [][]= new String [20][20];    
    int x;
    int y;
    int casilla=-1;
    Busqueda busca;
    
    public ventana() {
        busca=new Busqueda(d);
        initComponents();
        btnInicio.setEnabled(false);
        BtnMeta.setEnabled(false);
        BtnBlock.setEnabled(false);
        generar.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSalir = new javax.swing.JToggleButton();
        BtnNva = new javax.swing.JToggleButton();
        btnInicio = new javax.swing.JToggleButton();
        BtnMeta = new javax.swing.JToggleButton();
        BtnBlock = new javax.swing.JToggleButton();
        generar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 500));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });

        BtnNva.setText("Nueva Partida");
        BtnNva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNvaMouseClicked(evt);
            }
        });
        BtnNva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNvaActionPerformed(evt);
            }
        });

        btnInicio.setText("Inicio");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        BtnMeta.setText("Meta");
        BtnMeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMetaMouseClicked(evt);
            }
        });
        BtnMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMetaActionPerformed(evt);
            }
        });

        BtnBlock.setText("Bloqueo");
        BtnBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBlockMouseClicked(evt);
            }
        });
        BtnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBlockActionPerformed(evt);
            }
        });

        generar.setText("Generar");
        generar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarMouseClicked(evt);
            }
        });
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnSalir))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInicio)
                            .addComponent(BtnMeta))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnNva)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generar)
                            .addComponent(BtnBlock))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BtnNva)
                .addGap(25, 25, 25)
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnMeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBlock)
                .addGap(18, 18, 18)
                .addComponent(generar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(BtnSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalirMouseClicked

    private void BtnNvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNvaMouseClicked
        // TODO add your handling code here:                                        
        

    }//GEN-LAST:event_BtnNvaMouseClicked

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioMouseClicked

    private void BtnMetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMetaMouseClicked
        
    }//GEN-LAST:event_BtnMetaMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
          
        //10,30=0,0 AUMENTOS EN 20 x=x+20*n y=y+20*n   
        JOptionPane.showMessageDialog(null, "Seleccione la casilla que es Inicio");
        casilla=0;
        
    }//GEN-LAST:event_btnInicioActionPerformed

    private void BtnNvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNvaActionPerformed
        Dibujos d = new Dibujos();
        int x=10;
        int y=430;
        int x1=10;
        int y1=10;
        
        for (int i = 0; i < 21; i++) {
            d.pintarLinea(this.getGraphics(),x,y,x1,y1);
            x=x+20;
            x1=x1+20;    
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        x=410;
        y=10;
        x1=10;
        y1=10;
        
        for (int i = 0; i < 22; i++) {
            d.pintarLinea(this.getGraphics(),x,y,x1,y1);
            y=y+20;
            y1=y1+20; 
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        BtnNva.setEnabled(false);
        btnInicio.setEnabled(true);
    }//GEN-LAST:event_BtnNvaActionPerformed

    private void BtnMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMetaActionPerformed
          
        //10,30=0,0 AUMENTOS EN 20 x=x+20*n y=y+20*n   
        JOptionPane.showMessageDialog(null, "Seleccione la casilla que es Meta");
        casilla=1;
        
    }//GEN-LAST:event_BtnMetaActionPerformed

    private void BtnBlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBlockMouseClicked
          
        //10,30=0,0 AUMENTOS EN 20 x=x+20*n y=y+20*n   
        JOptionPane.showMessageDialog(null, "Seleccione las casillas que son Ostaculos");
        casilla=2;
    }//GEN-LAST:event_BtnBlockMouseClicked

    private void BtnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBlockActionPerformed

    private void generarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_generarMouseClicked

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        for (int i = 0; i < mat.length; i++) {
            for (int j = 0; j < mat[0].length; j++) {
                if(mat[i][j]==null){                
                    mat[i][j]="-";
                }                
            }
        }
        ArrayList<Camino> grafo=new ArrayList<>();
        Camino camino;
        int nombre=0;
        int inicio=0;
        int meta=0;
        System.out.println("Creando grafo...");
        for (int y = 0; y < mat.length; y++) {
            for (int x = 0; x < mat.length; x++) {
                if(!mat[x][y].equals("*")){
//                    System.out.println("nombre: "+nombre);
                    if(mat[x][y].equals("I")){
                        inicio=nombre;
                    }
                    if(mat[x][y].equals("M")){
                        meta=nombre;
                    }
                    if(x+1<mat.length){
                        if(!mat[x+1][y].equals("*")){
                            camino=new Camino();
                            camino.de=nombre;
                            camino.a=x+1+y*20;
                            camino.costo=1;
                            grafo.add(camino);
//                            System.out.println("Primera: "+(x+1+y*20));
                        }
                    }
                    if(y+1<mat[x].length){
                        if(!mat[x][y+1].equals("*")){
                            camino=new Camino();
                            camino.de=nombre;
                            camino.a=x+(y+1)*20;
                            camino.costo=1;
                            grafo.add(camino);
//                            System.out.println("Segunda: "+(x+(y+1)*20));
                        }
                    }
                    if(x-1>=0){
                        if(!mat[x-1][y].equals("*")){
                            camino=new Camino();
                            camino.de=nombre;
                            camino.a=x-1+y*20;
                            camino.costo=1;
                            grafo.add(camino);
//                            System.out.println("Tercera: "+(x-1+y*20));
                        }
                    }
                    if(y-1>=0){
                        if(!mat[x][y-1].equals("*")){
                            camino=new Camino();
                            camino.de=nombre;
                            camino.a=x+(y-1)*20;
                            camino.costo=1;
                            grafo.add(camino);
//                            System.out.println("Cuarta: "+(x+(y-1)*20));
                        }
                    }
                }
                nombre++;
            }
        }
//        for (int i=0; i<grafo.size(); i++) {
//            camino=grafo.get(i);
//            System.out.println("camino de "+camino.de+" a "+camino.a);
//        }
        busca.setParametros(inicio, meta);
        busca.setGrafo(grafo);
        busca.iniciarBusqueda();
        btnInicio.setEnabled(false);
        BtnMeta.setEnabled(false);
        BtnBlock.setEnabled(false);
        generar.setEnabled(false);
        BtnNva.setEnabled(true);
    }//GEN-LAST:event_generarActionPerformed

    private void click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click
        int x2=evt.getX();
        int y2=evt.getY();
        if(x2<410 && x2>0 && y2<430 &&y2>0){
            x2=(x2-10)/20;
            y2=(y2-30)/20;

            x=(20*(x2))+10;
            y=(20*(y2))+30;

            int x1=20;
            int y1=20;
            
            switch(casilla){
                case 0:
                    mat[x2][y2]= "I";            
                    d.inicio(this.getGraphics(), x, y, x1, y1);
                    btnInicio.setEnabled(false);
                    BtnMeta.setEnabled(true);
                    casilla=-1;
                    break;
                case 1:
                    mat[x2][y2]= "M";                                      
                    d.fin(this.getGraphics(), x, y, x1, y1);
                    BtnMeta.setEnabled(false);
                    BtnBlock.setEnabled(true);
                    generar.setEnabled(true);
                    casilla=-1;
                    break;
                case 2:
                    mat[x2][y2]= "*";
                    d.bl(this.getGraphics(), x, y, x1, y1);
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_click

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnBlock;
    private javax.swing.JToggleButton BtnMeta;
    private javax.swing.JToggleButton BtnNva;
    private javax.swing.JToggleButton BtnSalir;
    private javax.swing.JToggleButton btnInicio;
    private javax.swing.JToggleButton generar;
    // End of variables declaration//GEN-END:variables
}
